"""
stats.py
--------
Uncertainty quantification for model comparison.

Motivation
----------
Reporting "33.10 dB vs 28.03 dB" as a point estimate says nothing about whether
the difference would survive a different validation split, a different random
seed, or a different draw of undersampling masks. With ~199 validation slices and
a per-slice PSNR standard deviation of several dB, the standard error on the
mean is large enough that small differences between architectures are not
resolvable — and *that* is a claim worth being able to make precisely.

Two tools cover the cases that arise here:

* :func:`bootstrap_ci` — a confidence interval on a single model's mean metric,
  making no distributional assumption.
* :func:`paired_permutation_test` — an exact-in-the-limit test of whether two
  models differ, exploiting the fact that both are evaluated on the *same*
  slices. Pairing removes between-slice variance, which dominates the
  between-model variance, and typically increases power by an order of
  magnitude over an unpaired test.

Everything here is pure numpy: no scipy dependency, and every function is
seedable so a reported interval is reproducible.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np


@dataclass(frozen=True)
class Interval:
    """A point estimate with a confidence interval."""

    mean: float
    low: float
    high: float
    level: float = 0.95

    def __str__(self) -> str:
        return f"{self.mean:.4f} [{self.low:.4f}, {self.high:.4f}]"

    def as_dict(self) -> dict[str, float]:
        return {"mean": self.mean, "ci_low": self.low, "ci_high": self.high, "level": self.level}


def bootstrap_ci(
    values: np.ndarray | list[float],
    n_boot: int = 10_000,
    level: float = 0.95,
    seed: int | None = 0,
) -> Interval:
    """
    Percentile bootstrap confidence interval for the mean.

    Parameters
    ----------
    values
        Per-sample metric values (e.g. per-slice PSNR).
    n_boot
        Number of bootstrap resamples.
    level
        Confidence level.
    seed
        RNG seed; fixed by default so a published interval is reproducible.

    Returns
    -------
    :class:`Interval` with the observed mean and the percentile bounds.
    """
    arr = np.asarray(values, dtype=np.float64)
    arr = arr[np.isfinite(arr)]
    if arr.size == 0:
        return Interval(float("nan"), float("nan"), float("nan"), level)
    if arr.size == 1:
        v = float(arr[0])
        return Interval(v, v, v, level)

    rng = np.random.default_rng(seed)
    # Vectorised resampling: (n_boot, n) index matrix in one shot.
    idx = rng.integers(0, arr.size, size=(n_boot, arr.size))
    means = arr[idx].mean(axis=1)

    alpha = (1.0 - level) / 2.0
    low, high = np.quantile(means, [alpha, 1.0 - alpha])
    return Interval(float(arr.mean()), float(low), float(high), level)


def paired_permutation_test(
    a: np.ndarray | list[float],
    b: np.ndarray | list[float],
    n_perm: int = 10_000,
    seed: int | None = 0,
    alternative: str = "two-sided",
) -> dict[str, float]:
    """
    Paired permutation test on the mean difference ``a - b``.

    Both models must have been evaluated on the *same* samples in the *same*
    order. Under the null hypothesis of exchangeability, the sign of each paired
    difference is arbitrary, so the null distribution is generated by randomly
    flipping signs.

    Returns
    -------
    dict with ``mean_diff``, ``p_value``, ``n``, and the bootstrap CI bounds on
    the difference.
    """
    x = np.asarray(a, dtype=np.float64)
    y = np.asarray(b, dtype=np.float64)
    if x.shape != y.shape:
        raise ValueError(
            f"Paired test requires equal-length inputs, got {x.shape} and {y.shape}. "
            f"Both models must be evaluated on the same samples, in the same order."
        )

    diff = x - y
    diff = diff[np.isfinite(diff)]
    n = diff.size
    if n == 0:
        return {"mean_diff": float("nan"), "p_value": float("nan"), "n": 0}

    observed = float(diff.mean())
    rng = np.random.default_rng(seed)
    signs = rng.choice([-1.0, 1.0], size=(n_perm, n))
    null = (signs * diff).mean(axis=1)

    if alternative == "two-sided":
        extreme = np.abs(null) >= abs(observed)
    elif alternative == "greater":
        extreme = null >= observed
    elif alternative == "less":
        extreme = null <= observed
    else:
        raise ValueError(f"alternative must be two-sided, greater or less; got {alternative!r}")

    # (count + 1) / (n_perm + 1) is the standard unbiased estimator: it never
    # returns exactly 0, which would be an unsupportable claim from a finite
    # number of permutations.
    p_value = float((extreme.sum() + 1) / (n_perm + 1))

    ci = bootstrap_ci(diff, seed=seed)
    return {
        "mean_diff": observed,
        "p_value": p_value,
        "n": int(n),
        "diff_ci_low": ci.low,
        "diff_ci_high": ci.high,
        "cohens_d": float(observed / diff.std(ddof=1)) if n > 1 and diff.std() > 0 else 0.0,
    }


def holm_bonferroni(p_values: dict[str, float], alpha: float = 0.05) -> dict[str, dict]:
    """
    Holm-Bonferroni correction for a family of comparisons.

    Comparing three architectures pairwise means three tests, and taking the
    smallest p-value at face value inflates the false-positive rate. Holm is
    uniformly more powerful than plain Bonferroni and makes no independence
    assumption, so it is the right default for an ablation table.

    Returns
    -------
    ``{name: {"p": raw, "p_adjusted": adj, "significant": bool}}``
    """
    if not p_values:
        return {}

    ordered = sorted(p_values.items(), key=lambda kv: kv[1])
    m = len(ordered)
    results: dict[str, dict] = {}
    running_max = 0.0

    for i, (name, p) in enumerate(ordered):
        adjusted = min(1.0, (m - i) * p)
        # Enforce monotonicity: an adjusted p-value may never decrease as raw
        # p-values increase.
        running_max = max(running_max, adjusted)
        results[name] = {
            "p": float(p),
            "p_adjusted": float(running_max),
            "significant": bool(running_max < alpha),
        }
    return results


def compare_models(
    results: dict[str, dict[str, list[float]]],
    metric: str = "psnr",
    reference: str | None = None,
    n_boot: int = 10_000,
    seed: int | None = 0,
) -> dict:
    """
    Full statistical comparison across architectures.

    Parameters
    ----------
    results
        ``{model_name: {metric_name: [per-sample values]}}``. Every model must
        have been evaluated on the same samples in the same order.
    metric
        Which metric to compare.
    reference
        Baseline to compare against. Defaults to the first model.
    n_boot, seed
        Bootstrap settings.

    Returns
    -------
    dict with per-model intervals, pairwise tests against the reference, and
    Holm-adjusted p-values.
    """
    names = list(results)
    if not names:
        return {}
    reference = reference or names[0]
    if reference not in results:
        raise ValueError(f"reference {reference!r} not among {names}")

    intervals = {
        name: bootstrap_ci(results[name][metric], n_boot=n_boot, seed=seed).as_dict()
        for name in names
    }

    comparisons = {
        name: paired_permutation_test(
            results[name][metric], results[reference][metric], seed=seed
        )
        for name in names
        if name != reference
    }

    adjusted = holm_bonferroni({k: v["p_value"] for k, v in comparisons.items()})
    for name, adj in adjusted.items():
        comparisons[name].update(
            {"p_adjusted": adj["p_adjusted"], "significant": adj["significant"]}
        )

    return {
        "metric": metric,
        "reference": reference,
        "intervals": intervals,
        "comparisons": comparisons,
    }


def format_comparison_table(comparison: dict, precision: int = 4) -> str:
    """Render :func:`compare_models` output as a plain-text table."""
    if not comparison:
        return "(no results)"

    metric = comparison["metric"]
    reference = comparison["reference"]
    lines = [
        f"Metric: {metric}   Reference: {reference}",
        f"{'Model':<22}{'Mean':>10}{'95% CI':>24}{'Δ vs ref':>12}{'p (Holm)':>11}",
        "-" * 79,
    ]

    for name, iv in comparison["intervals"].items():
        ci = f"[{iv['ci_low']:.{precision}f}, {iv['ci_high']:.{precision}f}]"
        if name == reference:
            delta, pval = "—", "—"
        else:
            comp = comparison["comparisons"][name]
            delta = f"{comp['mean_diff']:+.{precision}f}"
            p = comp.get("p_adjusted", comp["p_value"])
            pval = f"{p:.4f}" + ("*" if comp.get("significant") else "")
        lines.append(
            f"{name:<22}{iv['mean']:>10.{precision}f}{ci:>24}{delta:>12}{pval:>11}"
        )

    lines.append("")
    lines.append("* significant at alpha = 0.05 after Holm-Bonferroni correction")
    return "\n".join(lines)
